name: Smart Plant System

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build:
    environment: pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

    - name: Test with pytest
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python -m pytest -v -W ignore::DeprecationWarning
